#!/usr/bin/env bash
# modules/vuln_network.sh — Network/crypto vulnerability checks
# Ports: test_ssl, spraying, api_key_validation

RAW="${WORKSPACE}/results/raw"
TMP="${WORKSPACE}/.tmp"

# ---------------------------------------------------------------------------
run_ssl_test() {
    local fn="run_ssl_test"
    [[ "${TEST_SSL:-true}" != "true" ]] && { skip_func "$fn" "disabled"; return 0; }
    already_done "$fn" && { skip_func "$fn" "processed"; return 0; }

    local testssl_bin
    testssl_bin=$(command -v testssl.sh 2>/dev/null || command -v testssl 2>/dev/null || \
                  echo "${TOOLS_DIR}/testssl.sh/testssl.sh")
    if [[ ! -x "$testssl_bin" ]]; then
        log_warn "ssl_test: testssl.sh not found — skipping"
        return 0
    fi

    local https_hosts="${WORKSPACE}/targets/https_hosts.txt"
    local ips="${WORKSPACE}/targets/ips.txt"
    local input_file=""
    [[ -s "$ips" ]]          && input_file="$ips"
    [[ -s "$https_hosts" ]]  && input_file="$https_hosts"
    if [[ -z "$input_file" ]]; then
        log_warn "ssl_test: no HTTPS hosts or IPs found"
        return 0
    fi

    start_func "$fn" "SSL/TLS Audit (testssl.sh)"
    local out="${RAW}/testssl.txt"
    run_tool "$testssl_bin" --quiet --color 0 -U -iL "$input_file" \
        2>>"${WORKSPACE}/logs/testssl.log" > "$out" || true

    grep -E 'VULNERABLE|WARN|NOT ok|CRITICAL' "$out" 2>/dev/null \
        | while IFS= read -r line; do
            local sev="medium"
            echo "$line" | grep -qi 'CRITICAL\|VULNERABLE' && sev="high"
            emit_finding "ssl_scan" "testssl.sh" "$sev" "SSL/TLS Issue" "ssl_scan" "$line"
        done || true

    # Also report certs expiring within 30 days from target_prep output
    local expiring="${WORKSPACE}/targets/expiring_certs.txt"
    if [[ -s "$expiring" ]]; then
        log_warn "  ⚠  Expiring/expired certificates found:"
        while IFS= read -r line; do
            log_warn "     $line"
            local host; host=$(echo "$line" | awk '{print $1}')
            local days; days=$(echo "$line" | grep -oP 'days_left=\K[0-9]+' || echo "0")
            local sev="medium"; [[ "$days" -le 7 ]] && sev="high"
            emit_finding "$host" "cert-expiry" "$sev" "Certificate Expiring/Expired" "$host" "$line"
        done < "$expiring"
    fi

    end_func "SSL audit complete → ${out}" "$fn"
}

# ---------------------------------------------------------------------------
# Generate a synthetic .gnmap from portMetadata JSON
# (replaces needing a live nmap run for password spraying input)
_synthesize_gnmap() {
    local gnmap_out="${TMP}/portscan_synth.gnmap"
    [[ -s "$gnmap_out" ]] && echo "$gnmap_out" && return 0

    local port_map="${WORKSPACE}/targets/port_map.json"
    [[ ! -s "$port_map" ]] && return 1

    # Write gnmap-compatible header
    printf "# Nmap synthetic output from asm_asset.json\n" > "$gnmap_out"
    printf "# Generated by Old_XTIP_ASM vuln_scan\n"      >> "$gnmap_out"

    # One gnmap line per host
    jq -r '
        . |
        (.ip // .subdomain) as $host |
        "Host: \($host) () Ports: " +
        ([ .ports[] | "\(.port)/open/tcp//\(.service)//" ] | join(", "))
    ' "$port_map" 2>/dev/null >> "$gnmap_out" || true

    [[ -s "$gnmap_out" ]] && echo "$gnmap_out" || return 1
}

# ---------------------------------------------------------------------------
run_password_spray() {
    local fn="run_password_spray"
    [[ "${SPRAYING:-false}" != "true" ]] && { skip_func "$fn" "disabled (SPRAYING=false)"; return 0; }
    already_done "$fn" && { skip_func "$fn" "processed"; return 0; }
    require_tool brutespray || return 0
    start_func "$fn" "Password Spraying (brutespray)"

    local gnmap; gnmap=$(_synthesize_gnmap)
    if [[ -z "$gnmap" || ! -s "$gnmap" ]]; then
        log_warn "spray: no port data available"
        end_func "Skipped — no port map" "$fn"; return 0
    fi

    ensure_dirs "${RAW}/brutespray"
    run_tool brutespray -f "$gnmap" \
        -T "${BRUTESPRAY_CONCURRENCE:-4}" \
        -o "${RAW}/brutespray" 2>>"${WORKSPACE}/logs/brutespray.log" || true

    end_func "Brutespray complete → ${RAW}/brutespray" "$fn"
}

# ---------------------------------------------------------------------------
run_api_key_validation() {
    local fn="run_api_key_validation"
    [[ "${API_KEY_VALIDATION:-true}" != "true" ]] && { skip_func "$fn" "disabled"; return 0; }
    already_done "$fn" && { skip_func "$fn" "processed"; return 0; }
    require_tool trufflehog || return 0
    start_func "$fn" "Active API Key/Secret Validation (TruffleHog)"

    local out="${RAW}/api_keys_validated.txt"; : > "$out"
    local js_dir="${WORKSPACE}/js"
    local url_file="${WORKSPACE}/urls/url_extract_nodupes.txt"

    if [[ -d "$js_dir" && "$(ls -A "$js_dir" 2>/dev/null)" ]]; then
        log_info "  Scanning JS directory for secrets..."
        run_tool trufflehog filesystem "$js_dir/" --json 2>/dev/null \
            | jq -r 'select(.Verified==true) |
                "[CRITICAL] Verified "+.DetectorName+" in "+.SourceName+" -> "+.Raw' \
            2>/dev/null >> "$out" || true
    fi

    if [[ -s "$url_file" ]]; then
        log_info "  Scanning URL extract for secrets..."
        run_tool trufflehog filesystem "$url_file" --json 2>/dev/null \
            | jq -r 'select(.Verified==true) |
                "[CRITICAL] Verified "+.DetectorName+" in "+.SourceName+" -> "+.Raw' \
            2>/dev/null >> "$out" || true
    fi

    sort -u "$out" -o "$out"
    while IFS= read -r line; do
        emit_finding "secrets" "trufflehog" "critical" "Active Verified Secret" "secrets" "$line"
    done < "$out"
    end_func "$(count_lines "$out") verified secrets → ${out}" "$fn"
}
